name: m1
dependencies:
  - apple::tensorflow-deps
  - black
  - bokeh
  - flask
  - jupyter
  - matplotlib
  - nodejs
  - numpy
  - pandas
  - pip
  - pylint
  - python
  - scikit-learn
  - seaborn
  - pip:
      - Flask-Testing
      - tensorboard
      - tensorflow-macos
      - tensorflow-metal
      - tensorflow-hub
